name: UI Web Automation Test

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  ui-web-automation-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 23

      - name: Give permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Run UI automation tests
        run: xvfb-run ./gradlew test

      - name: Upload Cucumber HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: build/reports/cucumber

      - name: Upload Gradle test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-test-report
          path: build/reports/tests/test
